application:
  name: damdev-blog

security:
  oauth2:
    client:
      clientId: damdev
      clientSecret: damdev-secret
      accessTokenValiditySeconds: 1    # 60*60*24 하루
      refreshTokenValiditySeconds: 2592000 # 60*60*24*30 30일

  #JWT signingKey 설정
  token:
    jwt:
      signingKey: damdev
